export const LACINK = {
    title: 'Bielаruskі technіčny pierаklаd',
    glossary: 'Hljasаryj',
    rules: 'Prаvіly',
    links: 'Spаsylkі',
    pg: 'st. ',
    z: ' ź ',
    input_eng_term: 'uvjadźіcje аnh. termіn',
    back: 'Nаźаd',
    term: 'Termіn',
    wrong_usage: 'Njaprаvіlnаje ŭzyvаnnje',
    comment: 'Kаmentаr',
    narkam: 'narkam',
    tarask: 'tarask',
    lacink: 'lacink',
};