export const LACINK = {
    title: 'Bielaruski techničny pieraklad',
    glossary: 'Hliasaryj',
    rules: 'Pravily',
    links: 'Spasylki',
    pg: 'st. ',
    z: ' ź ',
    input_eng_term: 'uviadźicie anh. termin',
    back: 'Naźad',
    term: 'Termin',
    wrong_usage: 'Niapraviĺnaje ŭzyvańnie',
    comment: 'Kamentar',
    narkam: 'narkam',
    tarask: 'tarask',
    lacink: 'lacink',
};