export const TARASK = {
    title: "Беларускі тэхнічны пераклад",
    glossary: "Глясарый",
    rules: "Правілы",
    links: "Спасылкі",
    pg: "ст. ",
    z: " з ",
    input_eng_term: "увядзіце анг. тэрмін",
    back: "Назад",
    term: "Тэрмін",
    wrong_usage: "Няправільнае ўжываньне",
    comment: "Камэнтар",
    narkam: "narkam",
    tarask: "tarask",
    lacink: "lacink",
};